services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: semantic-poc-app
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    env_file:
      - ../src/.env
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/embeddings_db
      - EMBEDDINGS_PROVIDER
      - OPENAI_API_KEY
      - OPENAI_EMBEDDING_MODEL
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: pgvector/pgvector:pg16
    container_name: semantic-poc-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: embeddings_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: semantic-poc-adminer
    depends_on:
      - db
    ports:
      - "9099:8080"

  ollama:
    image: ollama/ollama:latest
    container_name: semantic-poc-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "ollama serve &
       sleep 5 &&
       ollama pull nomic-embed-text &&
       wait"

volumes:
  db_data:
  ollama_data:
